project: 
  type: website
  output-dir: _site
 
execute:
  freeze: true  # never re-execute computational content during project render, needed for .qmd and .rmd since quarto does not render .ipynb by default
  
website: 
  page-navigation: true
  title: "PO.DAAC Cookbook" 
  site-url: "https://podaac.github.io/tutorials/" 
  repo-url: https://github.com/podaac/tutorials
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; PO.DAAC, 2022"
    
  sidebar:
    logo: "images/podaac-logo.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://podaac.jpl.nasa.gov/
        text: "PO.DAAC Website"
      - icon: github
        href: https://github.com/podaac/tutorials
        text: "Github Repository"        
    
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: quarto_text/index.qmd
        text: "Welcome"
      - href: quarto_text/HowTo.qmd 
        text: "How To's"
      - section: quarto_text/Tutorials.qmd 
        contents:
          - section: quarto_text/DatasetSpecificExamples.qmd
            contents:
              - section: quarto_text/SWOT.qmd
                contents:
                  - section: "Search"
                    contents:
                      - text: "By SWORD ID"
                        href: notebooks/SWORD_River_Demo.ipynb
                      - text: "By HUC ID"
                        href: notebooks/HUC Feature Translation Service Examples-updated-20210804.ipynb
                  - text: "Download/Subscribe"
                    href:
                  - section: "In-cloud Access"
                    contents:
                      - text: "Sample SWOT Hydrology Data"
                        href: notebooks/meetings_workshops/swot_ea_workshop_sept2022/SWOTHR_s3Access.ipynb
                      - text: "Sample SWOT Oceanography Data"
                        href: 
                  - text: "GIS Workflows"
                    href: notebooks/GIS/SWOTsample_GISshapefiles.ipynb
                  - section: "Transform Data"
                    contents:
                      - text: "Hydrology Time Series"
                        href: notebooks/GIS/SWOTsample_CSVconversion.ipynb
                      - text: "Subset by Bounding Box"
                        href: 
              - text: "ECCO" 
                href: notebooks/meetings_workshops/workshop_osm_2022/ECCO_ssh_sst_corr.ipynb
              - text: "GRACE/FO" 
                href: 
              - section: "Sentinel-6 MF" 
                contents: 
                  - text: "Access by Cycle/Pass"
                    href: notebooks/sentinel-6/Access_Sentinel6_By_CyclePass.ipynb               
                  - text: "Access NRT Data"
                    href: notebooks/sentinel-6/Access_Sentinel6_NRT.ipynb              
                  - text: "OPeNDAP Access"
                    href: notebooks/meetings_workshops/workshop_osm_2022/S6_OPeNDAP_Access_Gridding.ipynb
          - section: quarto_text/CloudvsLocalWorkflows.qmd
            contents:
              - section: "Estuary Example"
                contents:
                  - text: "Cloud"
                    href: notebooks/meetings_workshops/workshop_osm_2022/CloudAWS_AmazonRiver_Estuary_Exploration.ipynb
                  - text: "Local"
                    href: notebooks/meetings_workshops/workshop_osm_2022/Cloud_DirectDownload_AmazonRiver_Estuary_Exploration.ipynb
              - section: "Reservoir Example"
                contents:
                  - text: "Cloud"
                    href: notebooks/meetings_workshops/swot_ea_hackweek_2022/HLS-WaterDetection-Cloud.ipynb
                  - text: "Local"
                    href: notebooks/meetings_workshops/swot_ea_hackweek_2022/HLS-WaterDetection-Local.ipynb
          - section: quarto_text/PairingCloudNoncloudData.qmd
            contents:
              - text: "River Heights Comparison"
                href: notebooks/meetings_workshops/swot_ea_hackweek_2022/River_Heights_in_the_Cloud.ipynb
              - text: "Ocean Satellite & In-situ Comparison"
                href: notebooks/SWOT-EA-2021/Colocate_satellite_insitu_ocean.ipynb
          - section: quarto_text/CloudOptimizedExamples.qmd
            contents: 
              - text: "zarr-eosdis-store library"
                href: 
              - text: "zarr2netCDF" 
                href: 
      - href: quarto_text/Workshops.qmd
        text: "Workshops"
      - section: quarto_text/Webinars.qmd
        contents:
          - text: 
            href:
          - text: 
            href:  
      - section: quarto_text/TechGuides.qmd
        contents:
          - text: 
            href:
          - text: 
            href: 

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
